import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import localFont from 'next/font/local';
import "./globals.scss";
import { Navbar } from "@/components/navbar/Navbar";
import { FooterNavbar } from "@/components/footer-navbar/FooterNavbar";
import { CyberFrame } from "@/components/cyber-frame/CyberFrame";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const orbitron = localFont({
  src: '../public/fonts/Orbitron/Orbitron-VariableFont_wght.ttf',
  variable: '--font-orbitron',
  display: 'swap',
});

const firaCode = localFont({
  src: '../public/fonts/Fira_Code/FiraCode-VariableFont_wght.ttf',
  variable: '--font-firacode',
  display: 'swap',
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} ${orbitron.variable} ${firaCode.variable} h-full antialiased`}
    >
      <body className="min-h-full h-[100vh] p-6">
        <CyberFrame classNameContent="d-flex">
          <Navbar />
          <div className="flex-1 h-[90%]">{children}</div>
          <FooterNavbar />
        </CyberFrame>
      </body>
    </html>
  );
}
